version: '3.8'

services:
  # 1. Microservice Frontend (Admin Dashboard)
  admin-frontend:
    build:
      context: ../admin # Merujuk ke folder admin yang ada di luar/sebelah repo ini
    container_name: admin_app_container
    restart: always
    ports:
      - "80:80"

  # 2. Microservice Backend (Besosmed API)
  besosmed-backend:
    build:
      context: . # Merujuk ke folder besosmed (folder repo ini sendiri)
    container_name: besosmed_api_container
    restart: always
    ports:
      - "3000:3000" 
    env_file:
      - .env
    environment:
      - NODE_ENV=production
